app:
  rabbit:
    queue: EMAIL_SENDING_TASKS
#    exchange: email
#    routing_key: email

spring:
  rabbitmq:
    host: localhost
    username: admin
  mail:
    emailfrom: appjava33@gmail.com
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
#          ssl.trust: smtp.gmail.com
          starttls.enable: true
          starttls.required: true
#          ssl.enable: true
          timeout: 5000
          ssl.protocols: TLSv1.2
#          user: appjava33@gmail.com
        debug: true

#logging:
#  level:
#    root: DEBUG




